name: Report API CD
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "reports-api/**"
    

defaults:
  run:
    shell: bash
    working-directory: ./reports-api

jobs:
  setup-job:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - run: "true"
  
  invoke-webhook:
    if: github.repository == 'bcgov/EPIC-FLOW'
    needs: setup-job
    runs-on: ubuntu-20.04
    steps:
      - name: Workflow Webhook Action
        uses: distributhor/workflow-webhook@v2.0.3
        env:
          webhook_url: 'https://api.silver.devops.gov.bc.ca:6443/apis/build.openshift.io/v1/namespaces/dc383e-tools/buildconfigs/eao-project-reports-api-dev/webhooks/github-secret-key/github'
          webhook_secret: 'P@sw0rd'